### ISSUE TITLE
Enable/Disable Auto-scroll Dynamically (e.g. during run-time)?

### ISSUE THREAD

**Issue by gschmottlach-xse** [stevezau/ui-grid-auto-scroll#2]
I like your plugin but was wondering if you have considered adding the capability to enable/disable auto-scrolling dynamically? Looks like you only check the option when the plugin is initialized. Perhaps a better option might be to check it on every update or at least add an additional method that would enable/disable this feature during run-time.

Thoughts?

**Comment by stevezau** [comment]
Hi @gschmottlach-xse, yep i've thought about that but haven't had a need for it.

I'm happy to accept a PR?
